baseURL = ''
title = 'pismenost.online'
theme = 'digitalgarden'

googleAnalytics = 'G-Z5K3R6V0VN'

[Params]
  description = "Digitalan pismenost i sigurnost na internet"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
[[menu.main]]
  name = 'Sadr≈æaj'
  params.header = true
  weight = 1
[[menu.main]]
  name = 'Digitalna pismenost'
  url = '/articles'
  weight = 2
[[menu.main]]
  name = 'Zanimljivosti'
  url = '/portfolio'
  weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'
